package de.plmail.core.datastore

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import java.security.GeneralSecurityException
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import kotlin.io.encoding.Base64

/**
 * An encrypted secret, in the form it is stored in.
 *
 * A string rather than a `ByteArray` pair because this is what goes into DataStore, and because
 * `ByteArray` compares by identity — a `data class` holding two of them would have an `equals` that
 * silently answers false for two copies of the same secret.
 */
@JvmInline
value class SealedSecret(val encoded: String) {
    /** Never let a ciphertext reach a log by accident. */
    override fun toString(): String = "SealedSecret(…)"
}

/**
 * Encrypts the one secret the app cannot re-derive.
 *
 * An interface rather than a concrete Keystore class because the Android Keystore is not available
 * off-device: it has no JVM provider, so any test of the code *around* it — the store, onboarding,
 * the re-pair path — would need an emulator. The real implementation is exercised by an
 * instrumented test; everything above it takes this.
 */
interface SecretCipher {

    fun seal(plaintext: String): SealedSecret

    /**
     * Null when the ciphertext cannot be opened, which is a state the app has to survive rather
     * than an exception to propagate.
     *
     * Keystore keys do not leave the device and do not survive a factory reset, a restore onto new
     * hardware, or the key being invalidated underneath us. The stored bytes are then permanently
     * unreadable, and the only honest answer is to ask the user to pair again — a crash loop on
     * launch is the wrong one, and so is treating it as "no credential saved", which would silently
     * discard the server address they typed.
     */
    fun open(sealed: SealedSecret): String?
}

/**
 * [SecretCipher] over an AES-GCM key held in the Android Keystore.
 *
 * The key never leaves the secure hardware; only the ciphertext is written to DataStore. StrongBox
 * is requested when the device has it and silently declined when it does not — a phone without a
 * dedicated security chip is not a phone we refuse to run on.
 *
 * `setUserAuthenticationRequired(false)` deliberately: background sync and push both need to reach
 * the server while the screen is locked, and a key gated on unlock would turn every scheduled sync
 * into a failure the user only discovers when their mail is hours stale.
 */
class KeystoreSecretCipher(private val alias: String = DEFAULT_ALIAS) : SecretCipher {

    /**
     * Lazy, so loading the provider happens on whichever thread first opens a secret rather than on
     * whichever thread first *injects* something that holds this.
     *
     * That thread is the main one: this is a `@Singleton`, and the first component to ask for it is
     * `MainViewModel` during `onCreate`. `load(null)` is not free — it opens the keystore daemon
     * connection every later operation reuses — and paying for it here put it in front of the first
     * frame for no reason, since `CredentialStore` already does the opening itself off the main
     * thread.
     */
    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(PROVIDER).apply { load(null) }
    }

    override fun seal(plaintext: String): SealedSecret {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key())

        // The IV is generated by the Keystore, never by us, and is stored
        // alongside the ciphertext. Reusing one with GCM under the same key
        // destroys the mode's guarantees outright, so the safe move is to let
        // the provider pick and to keep what it picked.
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(plaintext.encodeToByteArray())

        return SealedSecret(Base64.Default.encode(iv + ciphertext))
    }

    override fun open(sealed: SealedSecret): String? =
        try {
            val bytes = Base64.Default.decode(sealed.encoded)
            if (bytes.size <= IV_LENGTH) return null

            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                key(),
                GCMParameterSpec(TAG_BITS, bytes, 0, IV_LENGTH),
            )

            cipher.doFinal(bytes, IV_LENGTH, bytes.size - IV_LENGTH).decodeToString()
        } catch (keyGone: GeneralSecurityException) {
            // The key was invalidated or never existed: a restore onto new
            // hardware, a factory reset, or the alias being cleared. Nothing
            // above can do anything with the distinction.
            null
        } catch (notBase64: IllegalArgumentException) {
            // The stored value is not decodable at all, which means it was
            // truncated or written by something other than seal().
            null
        }

    private fun key(): SecretKey = (keyStore.getKey(alias, null) as? SecretKey) ?: generateKey()

    private fun generateKey(): SecretKey {
        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)

        return try {
            generator.init(specBuilder().setIsStrongBoxBacked(true).build())
            generator.generateKey()
        } catch (noStrongBox: StrongBoxUnavailableException) {
            // Thrown at init time on devices without the dedicated chip. The
            // key is still hardware-backed by the TEE on everything we support;
            // StrongBox is an upgrade, not a requirement.
            generator.init(specBuilder().build())
            generator.generateKey()
        }
    }

    private fun specBuilder(): KeyGenParameterSpec.Builder =
        KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_BITS)
            .setUserAuthenticationRequired(false)
            // Randomised encryption is the default for GCM and is what forbids
            // a caller-supplied IV; stating it means a future edit that hands
            // one in fails here rather than at runtime on one device.
            .setRandomizedEncryptionRequired(true)

    companion object {
        const val DEFAULT_ALIAS = "plmail.credential"

        private const val PROVIDER = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val KEY_BITS = 256
        private const val TAG_BITS = 128

        /** GCM's standard nonce length, and what the Keystore provider emits. */
        private const val IV_LENGTH = 12
    }
}
