package de.plmail.feature.mail.reader

/**
 * What a message's own HTML says about colour.
 *
 * Read from the markup rather than rendered and sampled, because the decision has to be made before
 * the WebView loads anything — restyling after the fact means the user watches a white flash turn
 * dark, which is worse than either outcome on its own.
 *
 * Deliberately coarse. This is not a CSS parser and must not become one: it answers three
 * questions, each of which only has to be right often enough to pick a strategy that is *better*
 * than the alternatives, and every one of them has a "show original" escape hatch behind it.
 */
data class MessageColorProfile(
    /** The message has its own dark mode and only needs to be told which scheme is in use. */
    val declaresPrefersColorScheme: Boolean,
    /** Any explicit foreground or background colour anywhere in the markup. */
    val declaresColours: Boolean,
    /** Images, which invert badly and have to be inverted back. */
    val hasImagery: Boolean,
) {
    companion object {
        /**
         * Profiles a message body.
         *
         * Case-insensitive throughout: mail is generated by everything from Outlook to a shell
         * script, and `BGCOLOR="#FFFFFF"` is as common as the lower-case spelling.
         */
        fun of(html: String): MessageColorProfile {
            val lower = html.lowercase()

            return MessageColorProfile(
                declaresPrefersColorScheme = lower.contains("prefers-color-scheme"),
                declaresColours = COLOUR_MARKERS.any { it.containsMatchIn(lower) },
                hasImagery = IMAGERY_MARKERS.any { lower.contains(it) },
            )
        }

        /**
         * `bgcolor` and `background` are the presentational HTML attributes, still emitted by every
         * newsletter builder in existence; the rest are the CSS properties.
         *
         * The lookbehind on the bare `color` is load-bearing rather than pedantry. A plain
         * substring match also fires on `border-left-color`, `outline-color` and `caret-color`, so
         * a quoted reply whose only colour is a blockquote hairline would be pushed into inversion
         * — the worst-looking of the three strategies — for a border nobody would have noticed
         * either way. `background-color` stays explicitly listed because it genuinely does count.
         */
        private val COLOUR_MARKERS =
            listOf(
                Regex("background-color"),
                Regex("bgcolor"),
                Regex("background\\s*[:=]"),
                Regex("(?<![-a-z])color\\s*[:=]"),
            )

        private val IMAGERY_MARKERS =
            listOf("<img", "<picture", "<video", "<svg", "background-image")
    }
}

/**
 * How to render one message.
 *
 * Per message, not per thread and certainly not per app: a reply typed in a plain client and the
 * marketing mail it is quoting need different treatment, and they sit in the same conversation.
 */
enum class MessageRenderStyle {
    /** The message as sent. Always correct in a light theme, and the escape hatch in a dark one. */
    ORIGINAL,

    /**
     * Dark background and light text applied by us.
     *
     * The best-looking outcome, and only available when the message brought no colours of its own —
     * a plain reply, most mailing lists. Nothing is inverted, so images and logos are untouched.
     */
    DARK_RESTYLED,

    /**
     * The whole document inverted, then imagery inverted back.
     *
     * For messages that specify their own colours. Ugly in principle and much better than white
     * light in a dark room; the second inversion is the part everyone forgets, and without it every
     * photograph in the message comes out as a negative.
     */
    DARK_INVERTED,

    /**
     * The message has its own dark mode; tell it which scheme is in use and change nothing else.
     *
     * Always the best result when available, because the sender decided how their mail should look
     * in the dark rather than us guessing.
     */
    DARK_NATIVE,
}

/**
 * Picks a strategy.
 *
 * The order matters and is not arbitrary: a message that has done the work itself wins outright,
 * one that brought no colours can be restyled cleanly, and inversion is the last resort for
 * everything else.
 */
fun MessageColorProfile.styleFor(isDarkTheme: Boolean): MessageRenderStyle =
    when {
        // Never touch a message in a light theme. The user's theme is not the
        // sender's problem, and "dark mode" is the only reason to rewrite
        // anyone's markup at all.
        !isDarkTheme -> MessageRenderStyle.ORIGINAL
        declaresPrefersColorScheme -> MessageRenderStyle.DARK_NATIVE
        !declaresColours -> MessageRenderStyle.DARK_RESTYLED
        else -> MessageRenderStyle.DARK_INVERTED
    }

/**
 * Whether the reader should offer "show original" — true wherever the rendering was transformed.
 */
val MessageRenderStyle.isTransformed: Boolean
    get() = this != MessageRenderStyle.ORIGINAL && this != MessageRenderStyle.DARK_NATIVE
