package de.plmail.feature.mail.reader

import de.plmail.core.designsystem.PlMailThemeChoice
import de.plmail.core.designsystem.paletteFor
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Which rendering a message gets, over the three shapes real mail actually arrives in.
 *
 * A plain reply, a newsletter that sets its own colours, and a message that has already done the
 * work itself. Getting this wrong is not subtle — it is either a white rectangle in a dark room or
 * every photograph rendered as a negative.
 */
class MessageColorProfileTest {

    private val plainReply =
        """
        <div>Thanks, that works for me.</div>
        <blockquote>On Tuesday, Ada wrote:<br>Shall we say three?</blockquote>
        """

    private val newsletter =
        """
        <table bgcolor="#ffffff" width="600">
          <tr><td style="background-color:#f4f4f4; color:#333333">
            <img src="https://example.com/header.png" width="600">
            <h1 style="color:#111">This week</h1>
          </td></tr>
        </table>
        """

    private val selfDarkening =
        """
        <style>
          body { background: #fff; color: #111; }
          @media (prefers-color-scheme: dark) {
            body { background: #111; color: #eee; }
          }
        </style>
        <p>We handle dark mode ourselves.</p>
        """

    @Test
    fun `a light theme never rewrites anyone's markup`() {
        listOf(plainReply, newsletter, selfDarkening).forEach {
            assertEquals(
                MessageRenderStyle.ORIGINAL,
                MessageColorProfile.of(it).styleFor(isDarkTheme = false),
            )
        }
    }

    @Test
    fun `a plain reply is restyled rather than inverted`() {
        // The best-looking outcome: nothing is inverted, so nothing can come
        // out as a negative.
        assertEquals(
            MessageRenderStyle.DARK_RESTYLED,
            MessageColorProfile.of(plainReply).styleFor(isDarkTheme = true),
        )
    }

    @Test
    fun `a message that brought its own colours is inverted`() {
        assertEquals(
            MessageRenderStyle.DARK_INVERTED,
            MessageColorProfile.of(newsletter).styleFor(isDarkTheme = true),
        )
    }

    /**
     * The sender decided how their mail looks in the dark; we only tell it which scheme applies.
     */
    @Test
    fun `a message with its own dark mode wins outright`() {
        assertEquals(
            MessageRenderStyle.DARK_NATIVE,
            MessageColorProfile.of(selfDarkening).styleFor(isDarkTheme = true),
        )
    }

    /**
     * Its own dark mode beats having colours, and that ordering matters: a message that declares
     * `prefers-color-scheme` almost always also sets colours for the light case, so a rule that
     * checked colours first would invert every well-behaved message in existence.
     */
    @Test
    fun `declaring a scheme outranks declaring colours`() {
        val both =
            """
            <style>
              body { background-color: #ffffff; color: #000; }
              @media (prefers-color-scheme: dark) { body { background-color: #000; } }
            </style>
            """

        assertEquals(
            MessageRenderStyle.DARK_NATIVE,
            MessageColorProfile.of(both).styleFor(isDarkTheme = true),
        )
    }

    @Test
    fun `presentational attributes count as colours`() {
        // Mail is generated by everything from Outlook to a shell script, and
        // BGCOLOR in capitals is as common as the CSS spelling.
        val outlookish = """<TABLE BGCOLOR="#FFFFFF"><TR><TD>Hello</TD></TR></TABLE>"""

        assertTrue(MessageColorProfile.of(outlookish).declaresColours)
        assertEquals(
            MessageRenderStyle.DARK_INVERTED,
            MessageColorProfile.of(outlookish).styleFor(isDarkTheme = true),
        )
    }

    /**
     * A table border is not "bringing your own colours".
     *
     * Treating it as such would push a plain quoted reply into inversion for one hairline, and
     * inversion is the worst-looking of the three.
     */
    @Test
    fun `a border colour alone does not force inversion`() {
        val quoted =
            """<blockquote style="border-left-color:#ccc">Shall we say three?</blockquote>"""

        assertFalse(MessageColorProfile.of(quoted).declaresColours)
        assertEquals(
            MessageRenderStyle.DARK_RESTYLED,
            MessageColorProfile.of(quoted).styleFor(isDarkTheme = true),
        )
    }

    @Test
    fun `imagery is detected in every form that inverts badly`() {
        listOf(
                "<img src=x>",
                "<picture><source srcset=x></picture>",
                "<video src=x>",
                "<svg><rect/></svg>",
                """<div style="background-image:url(x)">""",
            )
            .forEach { assertTrue(MessageColorProfile.of(it).hasImagery, "missed: $it") }

        assertFalse(MessageColorProfile.of(plainReply).hasImagery)
    }

    @Test
    fun `only the transformed styles offer show original`() {
        assertFalse(MessageRenderStyle.ORIGINAL.isTransformed)
        // The sender's own dark mode is not our transformation, so there is
        // nothing to "show the original" of.
        assertFalse(MessageRenderStyle.DARK_NATIVE.isTransformed)
        assertTrue(MessageRenderStyle.DARK_RESTYLED.isTransformed)
        assertTrue(MessageRenderStyle.DARK_INVERTED.isTransformed)
    }
}

/**
 * The document that reaches the WebView.
 *
 * These are string assertions over a stylesheet, which is normally a poor kind of test — but the
 * previous version of this class shows why they are worth writing carefully rather than not at all.
 * It asserted that `max-width: 100% !important` was present and called the case "wide content
 * cannot force a horizontal scroll". It passed for the whole time a receipt's amounts were being
 * clipped off the right-hand edge of the pane, because `max-width` is not what fits a message: a
 * table cell with a specified width raises its column's *minimum*, and no `max-width` can shrink a
 * box below its minimum. So each case below names the failure it would catch rather than the
 * declaration it happens to find.
 */
class MessageDocumentTest {

    private val body = "<p>Hello</p><img src=\"cid:logo\">"

    /** A palette with values nothing else in the document could coincidentally contain. */
    private val palette =
        MessagePalette(
            paper = "#101112",
            ink = "#131415",
            inkMuted = "#161718",
            link = "#191A1B",
            line = "#1C1D1E",
            isDark = true,
        )

    private fun wrap(style: MessageRenderStyle) = MessageDocument.wrap(body, style, palette)

    /**
     * The rule the reported bug turned on.
     *
     * A receipt whose columns are `<td width="380">` is pinned at 760px by the table algorithm and
     * overflows a phone whatever else is in the stylesheet — labels render, the amounts beside them
     * do not. Releasing the specified widths is the only thing that lets it reflow.
     */
    @Test
    fun `table cells cannot pin a table wider than the pane`() {
        assertTrue(
            wrap(MessageRenderStyle.ORIGINAL).contains("td, th, col, colgroup { width: auto"),
            "cell widths are not released, so a fixed-width table will clip its right-hand column",
        )
    }

    /**
     * The image cap has to be a length, not a percentage.
     *
     * A percentage `max-width` is ignored while an element's intrinsic contribution is computed, so
     * a 2000px banner still sizes the table around it. `vw` resolves at that moment and a
     * percentage does not, which is the entire reason this rule looks unusual.
     */
    @Test
    fun `images are capped in viewport units`() {
        assertTrue(
            wrap(MessageRenderStyle.ORIGINAL).contains("max-width: min(100%, calc(100vw -"),
            "a percentage-only cap does not constrain a wide image's intrinsic width",
        )
    }

    /**
     * The wrapper's padding and the width an image may reach are one number twice.
     *
     * Drift between them is invisible in review and shows up as a sliver of the sender's background
     * on the right of every message with a full-width image — read out of the CSS here rather than
     * asserted as a literal, so the test fails on disagreement rather than on a value changing.
     */
    @Test
    fun `the inset and the viewport cap agree`() {
        val css = wrap(MessageRenderStyle.ORIGINAL)

        val padding = Regex("padding: (\\d+)px").find(css)?.groupValues?.get(1)?.toInt()
        val subtracted = Regex("calc\\(100vw - (\\d+)px\\)").find(css)?.groupValues?.get(1)?.toInt()

        assertEquals(padding?.times(2), subtracted, "the wrapper inset and the vw cap have drifted")
    }

    /**
     * The page must never scroll sideways; the message may.
     *
     * `overflow` on `body` propagates to the viewport, so putting the scroller there would drag the
     * whole page — and with it the reader's vertical gesture — rather than the message.
     */
    @Test
    fun `the message scrolls horizontally, not the page`() {
        val css = wrap(MessageRenderStyle.ORIGINAL)

        assertTrue(css.contains("<body><div id=\"plmail-message-root\">$body</div></body>"))
        assertTrue(css.contains("#plmail-message-root {"))
        assertTrue(css.substringAfter("#plmail-message-root {").contains("overflow-x: auto"))
        assertFalse(
            Regex("^\\s*(html|body)[^{]*\\{[^}]*overflow", RegexOption.MULTILINE)
                .containsMatchIn(css),
            "overflow on html or body propagates to the viewport: $css",
        )
    }

    @Test
    fun `inversion inverts imagery back`() {
        val html = wrap(MessageRenderStyle.DARK_INVERTED)

        assertTrue(html.contains("#plmail-message-root { filter: invert(1) hue-rotate(180deg)"))
        assertTrue(
            html.contains("img, picture, video, svg, [style*=\"background-image\"]"),
            "imagery is not inverted back: $html",
        )
    }

    /**
     * Nothing in an adapted document may be a colour the theme does not have.
     *
     * The first version painted `#121212` and `#e6e6e6`, which are Material's near-black and
     * near-white and belong to none of this app's six themes — so a message adapted under Nord sat
     * on a grey rectangle inside a blue-grey app, and the strip of it showing through the
     * document's padding read as a black band down the edge of the message.
     */
    @Test
    fun `an adapted message uses the theme's own colours`() {
        val restyled = wrap(MessageRenderStyle.DARK_RESTYLED)

        assertFalse(restyled.contains("invert("), "restyling must not invert: $restyled")
        assertTrue(restyled.contains(palette.ink))
        assertTrue(restyled.contains(palette.link))
        assertTrue(restyled.contains(palette.line))

        // Every style that *adapts* anything. ORIGINAL is excluded deliberately
        // and is the one place a literal colour is still right: it paints the
        // white sheet the sender wrote against, which is not a theme decision.
        listOf(
                MessageRenderStyle.DARK_RESTYLED,
                MessageRenderStyle.DARK_INVERTED,
                MessageRenderStyle.DARK_NATIVE,
            )
            .forEach { style ->
                assertFalse(
                    Regex("#(121212|e6e6e6|9ecbff|3a3a3a|b8b8b8|ffffff)", RegexOption.IGNORE_CASE)
                        .containsMatchIn(wrap(style)),
                    "$style still carries a hardcoded colour",
                )
            }
    }

    /**
     * The adapted styles paint no background at all, and that is the point.
     *
     * The reader draws the card and the WebView is transparent, so an unpainted document takes the
     * card's colour by construction. Painting one here would be a second copy of the theme's paper
     * that has to keep agreeing with the first, and the way that fails is a seam exactly where the
     * sender's own background stops.
     */
    @Test
    fun `an adapted message paints no paper of its own`() {
        listOf(MessageRenderStyle.DARK_RESTYLED, MessageRenderStyle.DARK_INVERTED).forEach { style
            ->
            assertFalse(
                Regex("#plmail-message-root[^}]*background:").containsMatchIn(wrap(style)),
                "$style paints its own paper and will not match the card behind it",
            )
        }
    }

    @Test
    fun `the original is left alone`() {
        val html =
            MessageDocument.wrap(body, MessageRenderStyle.ORIGINAL, palette.copy(isDark = false))

        assertFalse(html.contains("invert("))
        assertFalse(html.contains("color-scheme"))
        assertFalse(html.contains(palette.ink), "the original must not be recoloured")
        assertFalse(
            Regex("#plmail-message-root[^}]*background:").containsMatchIn(html),
            "a light theme must not paint paper the sender did not ask for",
        )
    }

    /**
     * "Show original" has to show something.
     *
     * It is the escape hatch from adaptation, and in a dark theme it is the *only* way this style
     * is reached — so a message that declares no background of its own would otherwise render the
     * user agent's near-black default text straight onto the card, which under Nord is a dark
     * blue-grey. The message would be there, be correct, and be unreadable.
     */
    @Test
    fun `asking for the original in the dark puts it on paper`() {
        assertTrue(
            Regex("#plmail-message-root \\{ background: #ffffff")
                .containsMatchIn(wrap(MessageRenderStyle.ORIGINAL)),
            "the unadapted message has no paper and will be black on a dark card",
        )
    }

    /**
     * `color-scheme` only where the message asked for it.
     *
     * Setting it on a message with no dark mode recolours form controls and scrollbars against a
     * body that stayed white.
     */
    @Test
    fun `the colour scheme is declared only for a self-darkening message`() {
        assertTrue(wrap(MessageRenderStyle.DARK_NATIVE).contains("color-scheme: dark"))
        assertFalse(wrap(MessageRenderStyle.DARK_RESTYLED).contains("color-scheme"))
    }

    @Test
    fun `the body is embedded rather than escaped`() {
        // Escaping it would render the mail as source code. The server
        // sanitises; the WebView sandbox is what makes that safe.
        assertTrue(wrap(MessageRenderStyle.ORIGINAL).contains(body))
    }
}

/** The bridge from the theme's tokens to the two dozen bytes of CSS a message is adapted with. */
class MessagePaletteTest {

    @Test
    fun `colours are emitted as six-digit hex`() {
        val palette = MessagePalette.of(paletteFor(PlMailThemeChoice.NORD, isDark = true))

        listOf(palette.paper, palette.ink, palette.inkMuted, palette.link, palette.line).forEach {
            assertTrue(
                Regex("^#[0-9A-F]{6}$").matches(it),
                "$it is not a CSS colour — alpha or a short form would be dropped by the parser",
            )
        }
    }

    /**
     * Every theme resolves to a different paper, which is the whole point of the change.
     *
     * Adapted messages used to land on one hardcoded near-black whatever the app looked like. If
     * two themes ever produced the same paper here, a message would stop following the theme again
     * and nothing else would notice.
     */
    @Test
    fun `each dark theme adapts a message onto its own paper`() {
        val papers =
            listOf(PlMailThemeChoice.DARK, PlMailThemeChoice.NORD, PlMailThemeChoice.DUSK).map {
                MessagePalette.of(paletteFor(it, isDark = true)).paper
            }

        assertEquals(papers.size, papers.toSet().size, "two themes share a message background")
    }
}
