package de.plmail.feature.mail.reader

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Which rendering a message gets, over the three shapes real mail actually arrives in.
 *
 * A plain reply, a newsletter that sets its own colours, and a message that has already done the
 * work itself. Getting this wrong is not subtle — it is either a white rectangle in a dark room or
 * every photograph rendered as a negative.
 */
class MessageColorProfileTest {

    private val plainReply =
        """
        <div>Thanks, that works for me.</div>
        <blockquote>On Tuesday, Ada wrote:<br>Shall we say three?</blockquote>
        """

    private val newsletter =
        """
        <table bgcolor="#ffffff" width="600">
          <tr><td style="background-color:#f4f4f4; color:#333333">
            <img src="https://example.com/header.png" width="600">
            <h1 style="color:#111">This week</h1>
          </td></tr>
        </table>
        """

    private val selfDarkening =
        """
        <style>
          body { background: #fff; color: #111; }
          @media (prefers-color-scheme: dark) {
            body { background: #111; color: #eee; }
          }
        </style>
        <p>We handle dark mode ourselves.</p>
        """

    @Test
    fun `a light theme never rewrites anyone's markup`() {
        listOf(plainReply, newsletter, selfDarkening).forEach {
            assertEquals(
                MessageRenderStyle.ORIGINAL,
                MessageColorProfile.of(it).styleFor(isDarkTheme = false),
            )
        }
    }

    @Test
    fun `a plain reply is restyled rather than inverted`() {
        // The best-looking outcome: nothing is inverted, so nothing can come
        // out as a negative.
        assertEquals(
            MessageRenderStyle.DARK_RESTYLED,
            MessageColorProfile.of(plainReply).styleFor(isDarkTheme = true),
        )
    }

    @Test
    fun `a message that brought its own colours is inverted`() {
        assertEquals(
            MessageRenderStyle.DARK_INVERTED,
            MessageColorProfile.of(newsletter).styleFor(isDarkTheme = true),
        )
    }

    /**
     * The sender decided how their mail looks in the dark; we only tell it which scheme applies.
     */
    @Test
    fun `a message with its own dark mode wins outright`() {
        assertEquals(
            MessageRenderStyle.DARK_NATIVE,
            MessageColorProfile.of(selfDarkening).styleFor(isDarkTheme = true),
        )
    }

    /**
     * Its own dark mode beats having colours, and that ordering matters: a message that declares
     * `prefers-color-scheme` almost always also sets colours for the light case, so a rule that
     * checked colours first would invert every well-behaved message in existence.
     */
    @Test
    fun `declaring a scheme outranks declaring colours`() {
        val both =
            """
            <style>
              body { background-color: #ffffff; color: #000; }
              @media (prefers-color-scheme: dark) { body { background-color: #000; } }
            </style>
            """

        assertEquals(
            MessageRenderStyle.DARK_NATIVE,
            MessageColorProfile.of(both).styleFor(isDarkTheme = true),
        )
    }

    @Test
    fun `presentational attributes count as colours`() {
        // Mail is generated by everything from Outlook to a shell script, and
        // BGCOLOR in capitals is as common as the CSS spelling.
        val outlookish = """<TABLE BGCOLOR="#FFFFFF"><TR><TD>Hello</TD></TR></TABLE>"""

        assertTrue(MessageColorProfile.of(outlookish).declaresColours)
        assertEquals(
            MessageRenderStyle.DARK_INVERTED,
            MessageColorProfile.of(outlookish).styleFor(isDarkTheme = true),
        )
    }

    /**
     * A table border is not "bringing your own colours".
     *
     * Treating it as such would push a plain quoted reply into inversion for one hairline, and
     * inversion is the worst-looking of the three.
     */
    @Test
    fun `a border colour alone does not force inversion`() {
        val quoted =
            """<blockquote style="border-left-color:#ccc">Shall we say three?</blockquote>"""

        assertFalse(MessageColorProfile.of(quoted).declaresColours)
        assertEquals(
            MessageRenderStyle.DARK_RESTYLED,
            MessageColorProfile.of(quoted).styleFor(isDarkTheme = true),
        )
    }

    @Test
    fun `imagery is detected in every form that inverts badly`() {
        listOf(
                "<img src=x>",
                "<picture><source srcset=x></picture>",
                "<video src=x>",
                "<svg><rect/></svg>",
                """<div style="background-image:url(x)">""",
            )
            .forEach { assertTrue(MessageColorProfile.of(it).hasImagery, "missed: $it") }

        assertFalse(MessageColorProfile.of(plainReply).hasImagery)
    }

    @Test
    fun `only the transformed styles offer show original`() {
        assertFalse(MessageRenderStyle.ORIGINAL.isTransformed)
        // The sender's own dark mode is not our transformation, so there is
        // nothing to "show the original" of.
        assertFalse(MessageRenderStyle.DARK_NATIVE.isTransformed)
        assertTrue(MessageRenderStyle.DARK_RESTYLED.isTransformed)
        assertTrue(MessageRenderStyle.DARK_INVERTED.isTransformed)
    }
}

/**
 * The document that reaches the WebView.
 *
 * The rule worth a test of its own is the second inversion: a document inverted without inverting
 * its imagery back renders every photograph as a negative, which is more obviously broken than the
 * white background it was meant to fix.
 */
class MessageDocumentTest {

    private val body = "<p>Hello</p><img src=\"cid:logo\">"

    @Test
    fun `inversion inverts imagery back`() {
        val html = MessageDocument.wrap(body, MessageRenderStyle.DARK_INVERTED)

        assertTrue(html.contains("body { filter: invert(1) hue-rotate(180deg)"))
        assertTrue(
            html.contains("img, picture, video, svg, [style*=\"background-image\"]"),
            "imagery is not inverted back: $html",
        )
    }

    @Test
    fun `a restyled message inverts nothing`() {
        val html = MessageDocument.wrap(body, MessageRenderStyle.DARK_RESTYLED)

        assertFalse(html.contains("invert("), "restyling must not invert: $html")
        assertTrue(html.contains("background: #121212"))
    }

    @Test
    fun `the original is left alone`() {
        val html = MessageDocument.wrap(body, MessageRenderStyle.ORIGINAL)

        assertFalse(html.contains("invert("))
        assertFalse(html.contains("#121212"))
        assertFalse(html.contains("color-scheme"))
    }

    /**
     * `color-scheme` only where the message asked for it.
     *
     * Setting it on a message with no dark mode recolours form controls and scrollbars against a
     * body that stayed white.
     */
    @Test
    fun `the colour scheme is declared only for a self-darkening message`() {
        assertTrue(
            MessageDocument.wrap(body, MessageRenderStyle.DARK_NATIVE)
                .contains("color-scheme: dark")
        )
        assertFalse(
            MessageDocument.wrap(body, MessageRenderStyle.DARK_RESTYLED).contains("color-scheme")
        )
    }

    @Test
    fun `the body is embedded rather than escaped`() {
        // Escaping it would render the mail as source code. The server
        // sanitises; the WebView sandbox is what makes that safe.
        assertTrue(MessageDocument.wrap(body, MessageRenderStyle.ORIGINAL).contains(body))
    }

    @Test
    fun `wide content cannot force a horizontal scroll`() {
        val html = MessageDocument.wrap(body, MessageRenderStyle.ORIGINAL)

        assertTrue(html.contains("max-width: 100% !important"))
    }
}
