package de.plmail

/**
 * The thirty-two logo colourways, and the launcher alias that wears each one.
 *
 * GENERATED by `tools/generate_launcher_icons.py` from `tools/logostyles.json`, which was extracted
 * by running the server's own `LogoStyle` enum rather than transcribed off a page. Add a colourway
 * by adding it there and rerunning the script: the icons, the aliases in the manifest and this file
 * all come out of that one table, and the point of generating them together is that they cannot
 * disagree.
 *
 * [wire] is the value the JMAP `Appearance` object carries in its read-only `logoStyle` property.
 * [alias] is the `<activity-alias>` that carries that colourway's icon, spelled out in full rather
 * than derived from [wire] at runtime — `android:name=".LogoLauncherBerry"` resolves against the
 * module's **namespace**, `de.plmail`, and not against the applicationId, which carries a flavour
 * suffix (`.google`) and a build-type one (`.debug`). The package half of a `ComponentName` is the
 * applicationId and the class half is this; getting that round the wrong way yields a component the
 * system has never heard of, and `setComponentEnabledSetting` on one of those throws.
 * `LogoStyleManifestTest` asserts every one of these strings against the merged manifest.
 *
 * The colours themselves are deliberately **not** here. Nothing in this app paints the mark — the
 * launcher does, out of the drawable the alias names — so a copy of the hexes in Kotlin would be a
 * copy that no code reads and nothing checks.
 */
enum class LogoStyle(val wire: String, val alias: String) {
    PRODUCT_BLUE("product-blue", "de.plmail.LogoLauncherProductBlue"),
    INK("ink", "de.plmail.LogoLauncherInk"),
    SLATE("slate", "de.plmail.LogoLauncherSlate"),
    FOREST("forest", "de.plmail.LogoLauncherForest"),
    BURGUNDY("burgundy", "de.plmail.LogoLauncherBurgundy"),
    DEEP_VIOLET("deep-violet", "de.plmail.LogoLauncherDeepViolet"),
    POSTAL("postal", "de.plmail.LogoLauncherPostal"),
    BRONZE_INK("bronze-ink", "de.plmail.LogoLauncherBronzeInk"),
    PETROL_COPPER("petrol-copper", "de.plmail.LogoLauncherPetrolCopper"),
    MIDNIGHT_GOLD("midnight-gold", "de.plmail.LogoLauncherMidnightGold"),
    NAVY_SKY("navy-sky", "de.plmail.LogoLauncherNavySky"),
    FOREST_LIME("forest-lime", "de.plmail.LogoLauncherForestLime"),
    PLUM_ROSE("plum-rose", "de.plmail.LogoLauncherPlumRose"),
    CHARCOAL_AMBER("charcoal-amber", "de.plmail.LogoLauncherCharcoalAmber"),
    ESPRESSO_CREAM("espresso-cream", "de.plmail.LogoLauncherEspressoCream"),
    COBALT_CORAL("cobalt-coral", "de.plmail.LogoLauncherCobaltCoral"),
    TEAL_GOLD("teal-gold", "de.plmail.LogoLauncherTealGold"),
    GRAPHITE_RED("graphite-red", "de.plmail.LogoLauncherGraphiteRed"),
    RED_FLICK("red-flick", "de.plmail.LogoLauncherRedFlick"),
    SKY_FLICK("sky-flick", "de.plmail.LogoLauncherSkyFlick"),
    BRONZE_FLICK("bronze-flick", "de.plmail.LogoLauncherBronzeFlick"),
    VIOLET_FLICK("violet-flick", "de.plmail.LogoLauncherVioletFlick"),
    TRICOLORE("tricolore", "de.plmail.LogoLauncherTricolore"),
    INDIGO_VIOLET("indigo-violet", "de.plmail.LogoLauncherIndigoViolet"),
    SUNSET("sunset", "de.plmail.LogoLauncherSunset"),
    OCEAN("ocean", "de.plmail.LogoLauncherOcean"),
    AURORA("aurora", "de.plmail.LogoLauncherAurora"),
    BERRY("berry", "de.plmail.LogoLauncherBerry"),
    EMBER("ember", "de.plmail.LogoLauncherEmber"),
    TWILIGHT("twilight", "de.plmail.LogoLauncherTwilight"),
    COPPER("copper", "de.plmail.LogoLauncherCopper"),
    BLUE_TONAL("blue-tonal", "de.plmail.LogoLauncherBlueTonal");

    companion object {

        /**
         * The colourway the product ships with, and the answer to every question this build cannot
         * answer.
         *
         * It is the server's own default, the ink in `ic_launcher_foreground`, the application's
         * `android:icon`, and the one alias the manifest enables. Those four being the same thing
         * is what makes an unknown colourway degrade to a correct icon rather than to no icon.
         */
        val Default: LogoStyle = BERRY

        /**
         * A wire name from the server, or [Default] for anything this build does not have.
         *
         * **Both absences are the same answer, and on purpose.** A server older than this feature
         * omits `logoStyle` entirely and arrives here as null; a server *newer* than this build can
         * send a colourway added after it shipped, and arrives here as a name no entry matches.
         * Neither is an error and neither may be a null: the value's only consumer switches a
         * launcher icon, so "I do not know this one" has to resolve to a real icon or the app is
         * one unrecognised string away from having none at all.
         */
        fun fromWire(wire: String?): LogoStyle = entries.firstOrNull { it.wire == wire } ?: Default
    }
}
